// Mocks generated by Mockito 5.4.0 from annotations
// in weathery/test/features/feature_bookmark/presentation/bloc/bookmark_block_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:weathery/core/params/no_param.dart' as _i8;
import 'package:weathery/core/resources/data_state.dart' as _i2;
import 'package:weathery/features/feature_bookmark/domain/entities/city_entity.dart'
    as _i5;
import 'package:weathery/features/feature_bookmark/domain/use_case/delete_city_usecase.dart'
    as _i9;
import 'package:weathery/features/feature_bookmark/domain/use_case/get_all_city_usecase.dart'
    as _i7;
import 'package:weathery/features/feature_bookmark/domain/use_case/get_city_usecase.dart'
    as _i3;
import 'package:weathery/features/feature_bookmark/domain/use_case/save_city_usecase.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetCityUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCityUseCase extends _i1.Mock implements _i3.GetCityUseCase {
  MockGetCityUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<_i5.City?>> call(String? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.DataState<_i5.City?>>.value(
            _FakeDataState_0<_i5.City?>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i5.City?>>);
}

/// A class which mocks [SaveCityUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveCityUseCase extends _i1.Mock implements _i6.SaveCityUseCase {
  MockSaveCityUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<_i5.City>> call(String? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.DataState<_i5.City>>.value(
            _FakeDataState_0<_i5.City>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i5.City>>);
}

/// A class which mocks [GetAllCityUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllCityUseCase extends _i1.Mock implements _i7.GetAllCityUseCase {
  MockGetAllCityUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<List<_i5.City>>> call(_i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.DataState<List<_i5.City>>>.value(
            _FakeDataState_0<List<_i5.City>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.DataState<List<_i5.City>>>);
}

/// A class which mocks [DeleteCityUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteCityUseCase extends _i1.Mock implements _i9.DeleteCityUseCase {
  MockDeleteCityUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<String>> call(String? params) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.DataState<String>>.value(_FakeDataState_0<String>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.DataState<String>>);
}
